# name: coverage
# on:
#   push:
#     branches:
#       - main
#       - master
#   pull_request:
# jobs:
#   golangci:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: golangci-lint
#         uses: golangci/golangci-lint-action@v6
#         with:
#           version: v1.59.1 # Use a specific version to ensure stability
#           # Optional: you can add a path to a custom configuration file
#           # config-file: .golangci.yml
